# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.permissions import AllowAny
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.utils.dateparse import parse_date
from rest_framework_jwt.settings import api_settings
import json
from django.core.serializers.json import DjangoJSONEncoder
import reportlab
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from reportlab.platypus import SimpleDocTemplate, Image
from reportlab.platypus.tables import Table
from reportlab.graphics.shapes import Line, Drawing

# line chart
"A 3D Column Chart"
#Autogenerated by ReportLab guiedit do not edit
from rlextra.graphics.quickchart import QuickChart
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin

class Drawing_000(_DrawingEditorMixin,Drawing):
  """
  3d Column Chart - with 3 series with grid lines
  """
  def __init__(self,width=400,height=200,*args,**kw):
    Drawing.__init__(self,width,height,*args,**kw)
    self._add(self,QuickChart(),name='chart',validate=None,desc=None)
    self.chart.height               = 200
    self.chart.seriesNames          ='a','b','c'
    self.chart.seriesRelation       = None#
    self.chart.dataLabelsFontSize   = 12
    self.chart.chartSeparation      = 1
    self.chart.data                 = [[100, 120, 140], [110, 130, 150],[200,100,100]]
    self.chart.titleText            = 'Column Chart'
    self.chart.xTitleText           = ''
    self.chart.categoryNames        = ('2009','2010','2012')
    self.chart.chartType='column3d'
    self.transform   = (1, 0, 0, 1, 0, 0)
    self.chart.xAxisGridLines       = 1
    self.chart.yAxisGridLines       = 1

if __name__=="__main__": #NORUNTESTS
  Drawing_000().save(formats=['pdf'],outDir='.',fnRoot=None)
cm = 2.54

# Create your views here.

class ReportsViewset(viewsets.ViewSet):
    permission_classes = (AllowAny,)

    def list(self, request):
      return JsonResponse({'GET': 'created'}, safe=False)

    def create(self, request):
      # Create the HttpResponse object with the appropriate PDF headers.
      content  = json.loads(request.body)
      print(content['report'])
      response = HttpResponse(content_type='application/pdf')
      response['Content-Disposition'] = 'attachment; filename=somefilename.pdf'

      elements = []

      content['report'].insert(0, ["kiloWatts/month", "date"])

      doc = SimpleDocTemplate(response, rightMargin=6.5, leftMargin=6.5, topMargin=15 * cm, bottomMargin=15 * cm)

      data=content['report']
      I = Image('assets/images/ql-logo.jpg', 500, 500)
      table = Table(data, colWidths=130, rowHeights=30)
      I.drawHeight =  15*cm
      I.drawWidth = 40*cm
      d = Drawing(800, 1)
      d.add(Line(0, 0, 570, 0))
      elements.append(I)
      elements.append(d)
      elements.append(table)
      print(SmileyMarkerChart)
      elements.append(Drawing_000())
      doc.build(elements) 
      return response



